CHANGELOG.md, app/app.go, appplus/app.go, go.mod, go.sum, x/wasm/keeper/test_common.go, x/wasmplus/keeper/genesis_test.go, x/wasmplus/keeper/test_common.go
- a7557b1d10: `bankplus.NewBaseKeeper()` wants one more argument which decides whether or not to disable `/cosmos.bank.v1beta1.MsgMultiSend`.
=> Bump line/lbm-sdk to a7557b1d10

CHANGELOG.md, x/wasmplus/types/codec.go, x/wasmplus/types/tx.go, x/wasmplus/types/tx_test.go
closes: #11 
1. When registering wasmplus amino codec, wrong message type name registered. currently "wasm/StoreCodeAndInstantiateContract", this should be "wasm/MsgStoreCodeAndInstantiateContract" like other messages.
2. When MsgStoreCodeAndInstantiateContract:: GetSignBytes is called wrong codec was called. currently wasm's codec is called which MsgStoreCodeAndInstantiateContract is not registered. wasmplus codec should be used.
=> fix wrong wasmplus amino codec register

CHANGELOG.md, go.mod, go.sum, x/wasm/module.go, x/wasm/module_test.go
closes: #13 
fix the cmd error that does not recognize wasmvm library version.
When we run the wasmd cli, `Error: wasmvm module not exist` is always displayed.
=> fix: fix the cmd error that does not recognize wasmvm library version.

CHANGELOG.md, go.mod, go.sum, x/wasm/ibctesting/chain.go, x/wasm/ibctesting/endpoint.go
closes: #20 
* bump up to [line/ibc-go v3.3.2](https://github.com/line/ibc-go/blob/v3.3.2/CHANGELOG.md#v332---20230403)
- apply the changes of line/ibc-go#6 (change to use `07-tendermint` instead of `99-ostracon`)
* replace the usage of Ostracon's ibc with Tendermint's
=> feat: bump up line/ibc-go v3.3.2

CHANGELOG.md, x/wasmplus/handler.go, x/wasmplus/module_test.go
fixes the bug wrapping twice the response of handling non-plus wasm message in plus handler.
wasmplus's handler returned a response that is wrapped twice (too much) when a non-plus wasm message is given.
This PR
- stops wrapping the response too much.
- adds tests handling non-plus wasm messages in wasmplus handler
- improve how to branch the handling of message
closes: #33 
closes: #34 
closes: #32
Unit-tests are added in this PR.
=> fix: stop wrap twice the response of handling non-plus wasm message in plus handler

CHANGELOG.md, x/wasm/keeper/keeper_test.go
closes: #39 
This test was moved from finschia-sdk by https://github.com/Finschia/wasmd/pull/1 and added by https://github.com/Finschia/finschia-sdk/pull/470.
Previously, a function called `UpdateContractStatus()` was used in https://github.com/Finschia/finschia-sdk/pull/470/commits/bde56b916605921468938c26ebd3155da12c4d54, 
but it was removed from wasmd and has become a meaningless test.
Further checking with https://github.com/Finschia/wasmd/issues/48, active/inactive management is done by wasmplus.
https://github.com/Finschia/wasmd/blob/ff18c5493565b88eb8cb1ecb5312218168110173/x/wasmplus/keeper/contract_keeper.go#L15-L16
In the test I deleted, "contract status", which was checked by `UpdateContractStatus()`, is not used in the current wasmd, so there is no problem in deleting it.
And …
=> fix: delete unnecessary test

CHANGELOG.md, x/wasm/README.md, x/wasm/keeper/keeper.go, x/wasm/keeper/keeper_test.go, x/wasm/keeper/test_common.go, x/wasm/types/events.go, x/wasm/types/types.pb.go
closes: #XXXX
ref. https://github.com/CosmWasm/wasmd/pull/1179
=> feat: add admin-related events

.github/workflows/test.yml, CHANGELOG.md, Makefile, x/wasm/client/testutil/cli_test.go, x/wasmplus/client/testutil/cli_test.go, x/wasmplus/client/testutil/testdata/wasm_genesis.json
* fix cli_test error of wasmplus 
* add cli_test and race in github action
We did not know the cli_test of wasmplus module had error. Because there is not in the ci as test. 
So, I fix this problem for adding to ci. 
The error is below
```bash
$ go test -tags="norace" ./x/wasmplus/client/testutil/...
--- FAIL: TestIntegrationTestSuite (0.01s)
suite.go:61: 
Error Trace:    /Users/zemyblue/Documents/project/blockchain/linkchain_v2/wasmd/x/wasmplus/client/testutil/suite.go:61
/Users/zemyblue/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:154
/Users/zemyblue/Documents/project/blockchain/linkchain_v2/wasmd/x/wasmplus/client/testutil/cli_test.go:32
Error:          Received unexpected error:
unknown field "instance_cost" in types.Params
Test:           TestIntegrationTestSuite
FAIL …
```
=> fix: fix cli_test error of wasmplus

CHANGELOG.md, init_single.sh, x/wasmplus/keeper/api.go, x/wasmplus/keeper/api_test.go
closes: #55
Though addresses given to dynamic link API are specified by contracts (users), it panics when address is invalid bech32 string. It should not panic and should handle it as an error.
By unit tests.
=> fix: fix dynamic link APIs do not panic with invalid bech32

.github/workflows/lint.yml, .github/workflows/test.yml, CHANGELOG.md, CONTRIBUTING.md, Dockerfile, README.md, contrib/prototools-docker/Dockerfile, go.mod, x/wasm/types/errors.go, x/wasm/types/test_fixtures.go
=> bulid: update golang version to 1.20

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
https://github.com/Finschia/wasmd/blob/main/docs/proto/proto-docs.md#msgstorecode
The event was not checked, so it was added to the test.
Also, here is a test on `instantiate_permission`.
https://github.com/Finschia/wasmd/blob/dedcd9ec5ba017f8a3591534ec099bc9097adb27/x/wasm/types/tx_test.go#L17-L79
=> test: add event checking to TestStoreCode

CHANGELOG.md, x/wasm/keeper/querier_test.go
Add a test case in each function because we have not tested if request is empty.
This PR has added tests for empty request in 6 functions, except contractsByCode(contractsByCode has not been tested, it will be fixed in another PR )
Unit tests
=> test: add test cases for empty request in each function

CHANGELOG.md, x/wasm/keeper/querier_test.go
Add a test case in some function because we have not tested if pagination key is invalid.
This PR has added tests for invalid pagination key in 3 functions, except contractsByCode(contractsByCode has not been tested, it will be fixed in another PR )
Unit tests
=> test: add test cases for invalid pagination key

CHANGELOG.md, x/wasm/client/testutil/query.go, x/wasm/keeper/legacy_querier.go, x/wasm/keeper/legacy_querier_test.go, x/wasm/keeper/querier.go, x/wasm/keeper/querier_test.go
Without this PR, `ContractHistory` always returns its' `Updated` field as nil.
This PR cherry-picks https://github.com/CosmWasm/wasmd/pull/1089/commits/9cbf64d967fa1298929b242defe9e4253ad82a21 and fixes `ContractHistory` legacy querier to fill the Updated field.
Unit tests
=> fix: fill ContractHistory querier result's Updated field

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
https://github.com/Finschia/wasmd/blob/main/docs/proto/proto-docs.md#msginstantiatecontract
This test is based on https://github.com/CosmWasm/wasmd/blob/33df4aeaaa419f6aad07b94d64c0423bee0a2d21/x/wasm/keeper/msg_server_integration_test.go#L827-L897
=> test: add event checking to TestInstantiateContract

CHANGELOG.md, x/wasm/keeper/querier_test.go
This PR is for checking this field.
https://github.com/Finschia/finschia-sdk/blob/ba75f8e7845a740afdce6e5f1c91f1a97433b7e2/proto/cosmos/base/query/v1beta1/pagination.proto#L54
=> test: add the check for `expPaginationTotal`

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
Fixes the bug in integration test when testing multiple specs in one test function.
In this pr, we use ctx.CacheContext() instead of ctx.
Fix the bug caused by #70
=> fix: use ctx cache in msg server integration test

CHANGELOG.md, x/wasm/keeper/querier_test.go
Add a test case to ContractHistory function which calls "with pagination next key", since we have not tested when setting pagination next key.
Unit tests
=> test: add pagination next key test in ContractHistory

CHANGELOG.md, x/wasmplus/keeper/querier_test.go
Add test case for `InactiveContract`
https://github.com/Finschia/wasmd/blob/main/docs/proto/proto-docs.md#lbm.wasm.v1.QueryInactiveContractRequest
https://github.com/Finschia/wasmd/blob/main/docs/proto/proto-docs.md#queryinactivecontractresponse
=> test: add the test case for InactiveContract

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
https://github.com/Finschia/wasmd/blob/main/docs/proto/proto-docs.md#msginstantiatecontract2
This PR adds an integration test for TestInstantiateContract2.
This test is based on https://github.com/CosmWasm/wasmd/blob/33df4aeaaa419f6aad07b94d64c0423bee0a2d21/x/wasm/keeper/msg_server_integration_test.go#L899-L976
=> test: add event checking to TestInstantiateContract2

CHANGELOG.md, x/wasm/client/testutil/query.go, x/wasm/keeper/legacy_querier.go, x/wasm/keeper/legacy_querier_test.go, x/wasm/keeper/querier.go, x/wasm/keeper/querier_test.go
This PR cherry-picking #62 into release/v0.1.x
=> fix: cherry-pick fill ContractHistory querier result's Updated field (#62)

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
https://github.com/Finschia/wasmd/blob/main/docs/proto/proto-docs.md#msgmigratecontract
This PR adds an integration test for TestMigrateContract.
This test is based on https://github.com/CosmWasm/wasmd/blob/33df4aeaaa419f6aad07b94d64c0423bee0a2d21/x/wasm/keeper/msg_server_integration_test.go#L740-L825
=> test: add event checking to TestMigrateContract

CHANGELOG.md, x/wasm/keeper/querier_test.go
Add a test case because we have not tested for Params.
```
// QueryParamsResponse is the response type for the Query/Params RPC method.
message QueryParamsResponse {
// params defines the parameters of the module.
Params params = 1 [ (gogoproto.nullable) = false ];
}
```
spec:
https://github.com/Finschia/wasmd/blob/main/proto/cosmwasm/wasm/v1/query.proto#L63
=> refactor: refactor test cases for Params

CHANGELOG.md, x/wasm/keeper/querier_test.go
Add test cases in function ContractsByCode because we have not tested it.
This PR adds 8 test cases to this function, including #65 and #66. 
Unit tests
=> test: add test cases in ContractsByCode

CHANGELOG.md, x/wasm/client/testutil/query.go, x/wasm/keeper/querier.go, x/wasm/keeper/querier_test.go
Without this PR, `ContractInfo` always returns its' `Updated` field as nil.
Unit tests
=> fix: fill ContractInfo result's Updated field

CHANGELOG.md, x/wasm/keeper/querier_test.go
delete output in TestQueryContractsByCode, caused by #71
=> fix: delete output in TestQueryContractsByCode

CHANGELOG.md, x/wasm/client/testutil/query.go, x/wasm/keeper/querier.go, x/wasm/keeper/querier_test.go
This PR cherry-picking #89 into release/v0.1.x
=> fix: cherry-pick fill ContractInfo result's Updated field (#89)

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
This PR adds an integration test for ExecuteContract.
This test is written for a test that depends on the hackatom contract.
The events added by hackatom contract are as follows.
https://github.com/Finschia/cosmwasm/blob/d86b54571ef7861964548241da6d8cbf6f77090f/contracts/hackatom/src/contract.rs#L94-L97
The destination address was not available on the msg_server, so I did not compare `events[2].Attributes[2].Value`
=> test: add an integration test for TestExecuteContract

x/wasm/keeper/querier_test.go
This PR adds a test case to verify ContractInfo gets correct IBCPortID
=> test: add a test case to verify ContractInfo gets correct IBCPortID

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go, x/wasmplus/keeper/msg_server_integration_test.go
Refactor TestStoreAndInstantiateContract
=> refactor: refactor TestStoreAndInstantiateContract

CHANGELOG.md, x/wasm/keeper/msg_server_integration_test.go
Refactor TestInstantiateContract, TestInstantiateContract2, TestMigrateContract, and TestExecuteContract
close https://github.com/Finschia/wasmd/issues/86
=> refactor tests for cosmwasm/wasm/v1/tx.proto other than TestClearAdmin

CHANGELOG.md, docs/proto/proto-docs.md, go.mod, proto/cosmwasm/wasm/v1/query.proto, x/wasm/types/query.pb.go
This PR adds clarifications to the order of list response in x/wasm query, which will make it easier for developers to understand the returned order.
closes: #91
=> docs: add clarifications to the order of list response in query

CHANGELOG.md, docs/proto/proto-docs.md, proto/lbm/wasm/v1/query.proto, x/wasmplus/types/query.pb.go
=> docs: add comment about ordering of addresses in wasmplus

CHANGELOG.md
* #61
* #84
* #63
* #65
* #66
* #64
* #70
* #73
* #72
* #75
* #74
* #78
* #69
* #71
* #82
* #87
* #79
* #88
* #76
* #68
* #99
* #98
* #100
* #62
* #52
* #89
* #90
* #95
* #101
* #104
* #60
* #105
* #109
* #54
* #92
* #103
* #107
=> Release wasmd v0.2.0

proto/buf.yaml
When you run `buf generate ./proto` in the root directory, you will receive the following warning: In fact, the dependency description is lacking.
```
WARN    bufimagebuild   File "cosmwasm/wasm/v1/query.proto" imports "google/api/annotations.proto", which is not found in your local files or direct dependencies, but is found in the transitive dependency "buf.build/googleapis/googleapis". Declare dependency "buf.build/googleapis/googleapis" in the deps key in buf.yaml.
```
This is a PR to correct this warning.
Declaring the dependency resolves the warning.
=> fix: declare dependency "buf.build/googleapis/googleapis"

CHANGELOG.md, go.mod, go.sum
This PR version-ups wasmvm (this version contains CWA-2023-004 patch)
=>  fix: version-up depending wasmvm to v1.1.1-0.12.0
